name: Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Base

      - name: Build base image
        run: docker build  ./docker -t pywear:latest
        
      - name: List docker images
        run: docker images

      - name: Rename base image tag for release
        run: docker tag pywear ghcr.io/sherazkhan/pywear

      - name: Push base image to github
        run: docker push ghcr.io/sherazkhan/pywear:latest
